version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: bp-dev-db
    environment:
      POSTGRES_DB: bp-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "3010:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
