services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: bpdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1                           
      - AWS_DEFAULT_REGION=us-east-1      
      - AWS_ACCESS_KEY_ID=test       
      - AWS_SECRET_ACCESS_KEY=test   

volumes:
  postgres_data: